---
- name: 'This is our first playbook'
  hosts: proxy
  gather_facts: true
  become: true
  vars:
    postgres_version: 11
    
  tasks:

    - name: 'Ping proxy servers'
      ping:

    - name: 'Create db backup log file'
      file:
        path: /var/log/dbbackup.log
        owner: root
        group: root
        mode: '0640'
        state: touch
    
    - name: 'Copy file index.html to server'
      copy:
        src: ../index.html
        dest: /srv/root.html
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'
    
    - name: 'Install admin packages'
      yum:
        name: 
          - bind-utils
          - tree
        state: present
    
    - name: Copy bash_profile
      template:
        src: ../bash_profile.j2
        dest: /home/vagrant/.bash_profile
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'

