- hosts: proxy
  become: true
  vars:
    nginx_port: 8080
    nginx_repo_path: /etc/yum.repos.d/nginx.repo

  tasks:

    - name: 'Create file for NGINX repo'
      file:
        path: "{{ nginx_repo_path }}"
        state: touch

    - name: 'Add official NGINX repo'
      blockinfile:
        path: "{{ nginx_repo_path }}"
        block: |
          [nginx-stable]
          name=nginx stable repo
          baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=https://nginx.org/keys/nginx_signing.key
          module_hotfixes=true 

    - name: 'Install NGINX'
      yum:
        name: nginx
        state: present

    - name: 'Start NGINX server'
      systemd:
        name: nginx
        state: started
        enabled: true
    
    - name: 'Copy index.html'
      template:
        src: ../templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: 'Copy default.conf'
      template:
        src: ../templates/default.conf.j2
        dest: /etc/nginx/conf.d/default.conf

    - name: 'Reload NGINX'
      shell: 'nginx -t && nginx -s reload'

    - name: 'Check that web-site working properly'
      uri:
        url: http://localhost:{{ nginx_port }}
        return_conten: true
      register: website
      failed_when: website.status != 200